sudo: required
language: java
jdk:
- openjdk8
services:
- docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
- test/run.sh
notifications:
  slack:
    secure: rVmHqHTIeMQeGEYAXA6spwM4Vo9whKOhG5FNaw1nYRfsDeSzgO1YYwjAsAXfqQIArAcIvJhjALv2iNrWz+dBNCyNXEhd0XhWlpkDy9kYJR7c79SvtotNEmG3qbarrScOfBKKlMmJYPtPa7JGdUdIVhVFOQg2CK7JBzlOTx12/M8=
