apiVersion: v1
kind: Service
metadata:
  name: complete-cluster-ip-service
  namespace: default
spec:
  selector:
    component: complete
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  sessionAffinity: None #CHANGE
  type: NodePort
